# Setup
title:               "Noel Rivas"
tagline:             "Software developer"
url:                 http://noelr.dev
baseurl:             ''
paginate:            5
permalink:           pretty

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
