# Setup
title:               "The Focus Quest"
tagline:             "Exploring distraction to find focus."
url:                 https://thefocus.quest
baseurl:             ''
paginate:            20
permalink:           pretty

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
gtm_id:             "G-LP6YCY2MC3"

timezone:           "America/Mexico_City"
