# Setup
title:               "Noel R"
tagline:             "I write code and get distracted a lot"
url:                 https://noelr.dev
baseurl:             ''
paginate:            20
permalink:           pretty

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
gtm_id:             "G-LP6YCY2MC3"

timezone:           "America/Mexico_City"
